{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.kimovoid",
    "module": "moderncontrols",
    "version": "1.0.0+b1.7.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "moderncontrols-1.0.0+b1.7.3.jar",
          "url": "moderncontrols-1.0.0+b1.7.3.jar",
          "size": 28779,
          "sha512": "de04af475efefd9bb43dc97239c67b702b1f580aac2652995e11af312d521f42eaf2fd36f107ac3420242c49aafc1c35f460efec4b9a1d64d343829922a300f9",
          "sha256": "2d497512668e79f8adb6b6c5f436d34febc30dc66b77bace39ec116e0cdf46b9",
          "sha1": "489e885c9dc7bb27179732cb8176301f66e0057d",
          "md5": "43cfab9b8a176c2ee9bac4312087a953"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.3"
          },
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.ornithemc.osl-gen2",
          "module": "localization",
          "version": {
            "requires": "0.1.0+mcb1.0-mc11w48a"
          },
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.ornithemc.osl-gen2",
          "module": "blocks",
          "version": {
            "requires": "0.1.1+mca1.0.1_01-mc1.6.4"
          },
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.ornithemc.osl-gen2",
          "module": "branding",
          "version": {
            "requires": "0.4.3+mca1.2.2-mc14w29b"
          },
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.ornithemc.osl-gen2",
          "module": "text-components",
          "version": {
            "requires": "0.1.0-alpha.3+mca0.1.0-mc1.14.4"
          },
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.ornithemc.osl-gen2",
          "module": "networking",
          "version": {
            "requires": "0.9.0+mcb1.0-mc13w39b"
          },
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.ornithemc.osl-gen2",
          "module": "core",
          "version": {
            "requires": "0.9.0+mca1.0.1_01-mc14w26c"
          },
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.ornithemc.osl-gen2",
          "module": "networking-impl",
          "version": {
            "requires": "0.1.1+mcb1.5-mc11w48a"
          },
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.ornithemc.osl-gen2",
          "module": "keybinds",
          "version": {
            "requires": "0.3.0+mca1.0.1_01-mcb1.7.3"
          },
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.ornithemc.osl-gen2",
          "module": "executors",
          "version": {
            "requires": "0.1.0+mcin-20100128-2304-mcb1.9-pre2"
          },
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.ornithemc.osl-gen2",
          "module": "entrypoints",
          "version": {
            "requires": "0.6.1+mca1.0.1_01-mc1.5.2"
          },
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.ornithemc.osl-gen2",
          "module": "lifecycle-events",
          "version": {
            "requires": "0.6.1+mcb1.3-mc12w17a"
          },
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.ornithemc.osl-gen2",
          "module": "config",
          "version": {
            "requires": "0.6.2+mcb1.3-mcb1.7.3"
          },
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.ornithemc.osl-gen2",
          "module": "items",
          "version": {
            "requires": "0.1.0+mca1.0.1_01-mc1.6.4"
          },
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.ornithemc.osl-gen2",
          "module": "resource-loader",
          "version": {
            "requires": "0.7.4+mca1.2.2-mc1.2.5"
          },
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ]
        },
        {
          "group": "io.github.kimovoid",
          "module": "reframed",
          "version": {
            "requires": "1.0.2+b1.7.3"
          },
          "excludes": [
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "moderncontrols-1.0.0+b1.7.3.jar",
          "url": "moderncontrols-1.0.0+b1.7.3.jar",
          "size": 28779,
          "sha512": "de04af475efefd9bb43dc97239c67b702b1f580aac2652995e11af312d521f42eaf2fd36f107ac3420242c49aafc1c35f460efec4b9a1d64d343829922a300f9",
          "sha256": "2d497512668e79f8adb6b6c5f436d34febc30dc66b77bace39ec116e0cdf46b9",
          "sha1": "489e885c9dc7bb27179732cb8176301f66e0057d",
          "md5": "43cfab9b8a176c2ee9bac4312087a953"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "moderncontrols-1.0.0+b1.7.3-sources.jar",
          "url": "moderncontrols-1.0.0+b1.7.3-sources.jar",
          "size": 17012,
          "sha512": "ccb2bf3b4e97567f1cab85b8cd4330cadda7825a0b36e3219fb5ce69819bcfdcf7b02f1d7cc889598d42deab1328b6659b5dfd69d5d1e4834f95baa51577dff6",
          "sha256": "02bd47dd70820406dc159301f47423f7d4f233244c77516cf67600dfea4f82ac",
          "sha1": "148a0a39b2c8bb56263e78acae4679dab54d5613",
          "md5": "d7059ec790fad839bef570e55596f9a8"
        }
      ]
    }
  ]
}
